'use client';
import { useEffect, useMemo, useState } from 'react';
import { calculateTotals } from '@/lib/utils';
import { parseMenuRequest } from '@/lib/ai/parser';
import { createClient } from '@/lib/supabase/browser';
import type { CartLine, MenuItem } from '@/types/domain';

export function CustomerOrderApp({ table, initialMenu }: { table: number | null; initialMenu: MenuItem[] }) {
  const [menu] = useState(initialMenu); const [cart, setCart] = useState<CartLine[]>([]); const [query, setQuery] = useState(''); const [language, setLanguage] = useState<'en'|'ta'>('en'); const [message, setMessage] = useState(''); const [currentOrder, setCurrentOrder] = useState<{ order_number:string; status:string } | null>(null); const [submitting, setSubmitting] = useState(false);
  const totals = calculateTotals(cart); const visible = useMemo(() => menu.filter(item => `${item.name} ${item.name_ta}`.toLowerCase().includes(query.toLowerCase())), [menu, query]);
  useEffect(() => { if (!currentOrder) return; const supabase=createClient(); const channel=supabase.channel(`customer-${currentOrder.order_number}`).on('postgres_changes',{event:'UPDATE',schema:'public',table:'orders',filter:`order_number=eq.${currentOrder.order_number}`},payload=>setCurrentOrder(payload.new as {order_number:string;status:string})).subscribe(); return () => { void supabase.removeChannel(channel); }; }, [currentOrder?.order_number]);
  function add(item: MenuItem, customizations: string[] = []) { setCart(lines => [...lines, { menuItem:item, quantity:1, customizations }]); }
  function askAI() { const result=parseMenuRequest(query,menu); if (result.needsClarification) return setMessage(language==='en'?'I could not match that to an available dish.':'கிடைக்கும் மெனுவில் அந்த உணவை கண்டறிய முடியவில்லை.'); result.items.forEach(line=>{const item=menu.find(candidate=>candidate.id===line.foodId);if(item)add(item,line.customizations);}); setMessage(language==='en'?'Matching items added to your cart.':'பொருத்தமான உணவுகள் கார்ட்டில் சேர்க்கப்பட்டன.'); }
  async function submitOrder() { if (!table || !cart.length || submitting) return; setSubmitting(true); const key=crypto.randomUUID(); const response=await fetch('/api/orders',{method:'POST',headers:{'content-type':'application/json','idempotency-key':key},body:JSON.stringify({table,session_id:sessionStorage.getItem('smartserve-session')||key,items:cart.map(line=>({menu_item_id:line.menuItem.id,quantity:line.quantity,customizations:line.customizations})),payment_method:'CASH'})}); const result=await response.json(); setSubmitting(false); if (!response.ok) return setMessage(result.error||'Order could not be placed.'); sessionStorage.setItem('smartserve-session',key); setCurrentOrder(result.data); setCart([]); setMessage(`Order ${result.data.order_number} received.`); }
  return <main className="container"><header style={{display:'flex',justifyContent:'space-between',gap:12,alignItems:'center',marginBottom:24}}><div><b style={{fontSize:22}}>Smart<span style={{color:'var(--success)'}}>Serve</span> AI</b><div style={{color:'var(--muted)',marginTop:5}}>{table?`Table ${table}`:'Table not identified - use a QR table URL'}</div></div><button className="button secondary" onClick={()=>setLanguage(language==='en'?'ta':'en')}>{language==='en'?'Tamil':'English'}</button></header>{!table&&<div className="card" style={{marginBottom:16,borderColor:'#f59e0b'}}>This QR link has no valid table. Use a URL such as <code>/order?table=7</code>.</div>}{currentOrder&&<section className="card" style={{marginBottom:16,borderColor:'var(--success)'}}><b>Order {currentOrder.order_number}</b><div style={{marginTop:8}} className="status ready">{currentOrder.status}</div></section>}<section className="card"><h1>{language==='en'?'Welcome. What would you like to order?':'வரவேற்கிறோம். என்ன ஆர்டர் செய்ய விரும்புகிறீர்கள்?'}</h1><input className="input" placeholder="Search available menu" value={query} onChange={e=>setQuery(e.target.value)}/><div style={{display:'flex',gap:8,marginTop:10}}><button className="button secondary" onClick={askAI}>Ask SmartServe AI</button>{message&&<span style={{color:'var(--muted)',alignSelf:'center'}}>{message}</span>}</div></section><div className="grid cols-2" style={{marginTop:16}}>{visible.map(item=><article className="card" key={item.id}><div style={{display:'flex',justifyContent:'space-between',gap:10}}><div><h2 style={{margin:'0 0 5px'}}>{language==='en'?item.name:item.name_ta}</h2><p style={{color:'var(--muted)',marginTop:0}}>{language==='en'?item.description:item.description_ta}</p></div><b>₹{item.price}</b></div><div style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><span className="status">{item.is_vegetarian?'VEG':'NON-VEG'} · {item.stock_quantity} available</span><button className="button" disabled={!table} onClick={()=>add(item)}>Add</button></div></article>)}</div><section className="card" style={{marginTop:16}}><h2>Your order</h2>{cart.length===0?<p style={{color:'var(--muted)'}}>Your cart is empty.</p>:cart.map((line,index)=><div key={`${line.menuItem.id}-${index}`} style={{display:'flex',justifyContent:'space-between',borderBottom:'1px solid var(--line)',padding:'10px 0'}}><span>{line.quantity} × {line.menuItem.name}<small style={{display:'block',color:'var(--muted)'}}>{line.customizations.join(', ')}</small></span><b>₹{line.menuItem.price*line.quantity}</b></div>)}<div style={{marginTop:14,textAlign:'right'}}>Subtotal ₹{totals.subtotal} · GST ₹{totals.tax} · <b>Total ₹{totals.total}</b></div><button className="button" disabled={!table||!cart.length||submitting} onClick={submitOrder} style={{marginTop:12,width:'100%'}}>{submitting?'Submitting...':'Place order'}</button></section></main>;
}
